### BEGIN C++ DEPENDENCIES
TestArray.o: TestArray.cpp ../../../src/include/config.h \
 ../../../src/libdjvu++/GContainer.h \
 ../../../src/libdjvu++/GException.h \
 ../../../src/libdjvu++/DjVuGlobal.h \
 ../../../src/include/DjVu.h \
 ../../../src/libdjvu++/GSmartPointer.h \
 ../../../src/libdjvu++/GString.h
TestBitmap.o: TestBitmap.cpp ../../../src/include/config.h \
 ../../../src/libdjvu++/GBitmap.h \
 ../../../src/libdjvu++/GSmartPointer.h \
 ../../../src/libdjvu++/DjVuGlobal.h \
 ../../../src/include/DjVu.h \
 ../../../src/libdjvu++/GException.h \
 ../../../src/libdjvu++/ByteStream.h \
 ../../../src/libdjvu++/Arrays.h
TestException.o: TestException.cpp \
 ../../../src/include/config.h ../../../src/libdjvu++/GException.h \
 ../../../src/libdjvu++/DjVuGlobal.h \
 ../../../src/include/DjVu.h \
 ../../../src/libdjvu++/GString.h \
 ../../../src/libdjvu++/GContainer.h \
 ../../../src/libdjvu++/GSmartPointer.h \
 ../../../src/libdjvu++/DjVuMessage.h \
 ../../../src/libdjvu++/DjVuMessageLite.h
TestJB2.o: TestJB2.cpp ../../../src/include/config.h \
 ../../../src/libdjvu++/JB2Image.h \
 ../../../src/libdjvu++/GString.h \
 ../../../src/libdjvu++/DjVuGlobal.h \
 ../../../src/include/DjVu.h \
 ../../../src/libdjvu++/GContainer.h \
 ../../../src/libdjvu++/GException.h \
 ../../../src/libdjvu++/GSmartPointer.h \
 ../../../src/libdjvu++/ZPCodec.h \
 ../../../src/libdjvu++/GBitmap.h \
 ../../../src/libdjvu++/ByteStream.h \
 ../../../src/libdjvu++/Arrays.h \
 ../../../src/libdjvu++/GURL.h \
 ../../../src/libdjvu++/GThreads.h
TestList.o: TestList.cpp ../../../src/include/config.h \
 ../../../src/libdjvu++/GContainer.h \
 ../../../src/libdjvu++/GException.h \
 ../../../src/libdjvu++/DjVuGlobal.h \
 ../../../src/include/DjVu.h \
 ../../../src/libdjvu++/GSmartPointer.h \
 ../../../src/libdjvu++/GString.h \
 ../../../src/libdjvu++/DjVuMessage.h \
 ../../../src/libdjvu++/DjVuMessageLite.h
TestMap.o: TestMap.cpp ../../../src/include/config.h \
 ../../../src/libdjvu++/GContainer.h \
 ../../../src/libdjvu++/GException.h \
 ../../../src/libdjvu++/DjVuGlobal.h \
 ../../../src/include/DjVu.h \
 ../../../src/libdjvu++/GSmartPointer.h \
 ../../../src/libdjvu++/GString.h
TestSmartPointer.o: TestSmartPointer.cpp \
 ../../../src/include/config.h \
 ../../../src/libdjvu++/GSmartPointer.h \
 ../../../src/libdjvu++/DjVuGlobal.h \
 ../../../src/include/DjVu.h
TestString.o: TestString.cpp ../../../src/include/config.h \
 ../../../src/libdjvu++/GString.h \
 ../../../src/libdjvu++/DjVuGlobal.h \
 ../../../src/include/DjVu.h \
 ../../../src/libdjvu++/GContainer.h \
 ../../../src/libdjvu++/GException.h \
 ../../../src/libdjvu++/GSmartPointer.h \
 ../../../src/libdjvu++/DjVuMessage.h \
 ../../../src/libdjvu++/DjVuMessageLite.h
TestThreads.o: TestThreads.cpp ../../../src/include/config.h \
 ../../../src/libdjvu++/GThreads.h \
 ../../../src/libdjvu++/DjVuGlobal.h \
 ../../../src/include/DjVu.h \
 ../../../src/libdjvu++/GException.h
### END   C++ DEPENDENCIES
