creating test-a
creating test-b
t2 contains test-b with counter 1
deleting test-b
t1 contains test-a with counter 1
creating test-c
deleting test-a
t1 contains test-c with counter 1
creating test-d
t4 contains test-c with counter 2
t3 contains test-d with counter 2
t1 contains test-d with counter 2
deleting test-c
t1 contains test-d with counter 1
creating test-e
t5 contains test-e with counter 1
arg contains test-e with counter 2
t5 contains test-e with counter 1
t5 contains test-e with counter 1
deleting test-e
deleting test-d
