gl1.size() :=3
( "one" "two" "three" )
gl1[pos] :="one"
gl1[pos] :="two"
( "zero" "one" "two" "three" )
( "one" "two" "three" )
(*gl)[pos] :="one"
( "zero" "one" "two" "three" )
n :=1
gl2[pos] :="two"
n :=1
gl2[pos] :="three"
n :=0
gl2[pos] :="three"
( "zero" "one" "two" "before three" "after three" )
gl1.size() :=3
( "one" "two" "three" )
n :=1
( 'after three' 'before three' 'two' 'one' 'zero' )
