gs1 :=""
gs2 :="abcdefghijklmnopqrstuvwxyz"
gs3 :="abcdefghijklmnopqrstuvwxyz"
gs4 :="abcd"
gs5 :="wxyz"
gs5 :="abcdefghijklmnopqrstuvwxyz"
gs5 :="ghijkl"
gs5.length() :=6
!gs5 ? 1 : 0 :=0
!gs1 ? 1 : 0 :=1
gs2[3] :=100 'd'
gs2[4] :=101 'e'
gs2[-1] :=122 'z'
gs3 :="abcdefghijklmnopqrstuvwxyz"
gs2 :="abcdefghijklmnopqrstuvwxyz"
gs2 :="abcdefghijklmnopqrstuvwxZz"
gs3 :="abcdefghijklmnopqrstuvwxyz"
gsu :="ABCDEFGHIJKLMNOPQRSTUVWXZZ"
gsu :="abcdefghijklmnopqrstuvwxzz"
gsu :=""
gsu :="hello folks from 314"
gsu.search('f') :=6
gsu.rsearch('f') :=12
gsu.search('f',8) :=12
gsu.search('z') :=-1
gsu.search("folks") :=6
gsu.rsearch(" f") :=11
gsu.rsearch(" f",8) :=5
gsu.rsearch(" f",3) :=-1
gs2 :="hello folks from 314"
gs3 :="abcdefghijklmnopqrstuvwxyz"
gs2==gsu :=1
gs2!=gsu :=0
gs2!=gs3 :=1
gs2<gs3 :=0
gs2>gs3 :=1
gs2 :="hello folks from 314efgh"
gs1 :="hello folks from 314 abcdefghijklmnopqrstuvwxyz"
gsa :="abcdef"
gsb :="abcdef"
gsa==gsb :=1
"abcdef"!=gsb :=0
gsa<gsb :=0
gsa<=gsb :=1
